### ISSUE TITLE
Colortuner + neovim + true colors results in weird behaviour on initial render

### ISSUE THREAD

**Issue by alexanderjeurissen** [zefei/vim-colortuner#3]
> NOTE: I initially opened this issue on the Cake16 project, but it seems that this issue is caused by colortuner as disabling the plugin remedies the issue described below. (https://github.com/zefei/cake16/issues/5)

When using neovim with `set termguicolors` the cake16 colorscheme and your colortuner plugin loading neovim with a file results in weird initial rendering, reloading vimrc or opening another file solves it.

to replicate this issue:
1. set cake16 as the colorscheme of neovim
2. enable true color support in `init.vim` with `set termguicolors`
3. install colortuner plugin and change some settings (so it persists the color modifications)
4. close neovim
5. open neovim by invoking it with a file path like this: `neovim ~/.zshrc` or `neovim ~/.bash-profile`
6. some text is blacked out like this screenshot:
![screen shot 2017-01-13 at 20 29 17](https://cloud.githubusercontent.com/assets/1220084/21942998/9b020256-d9cf-11e6-912a-9cee59c8c081.png)

**Comment by alexanderjeurissen** [comment]
I just tested with a minimal neovim config and can still replicate the issue above.

minimal neovim config:

```
"For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
"Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
" < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
if (has("termguicolors"))
  if(has("nvim"))
    set termguicolors
  endif
endif

set nocompatible               " Be iMproved

"Note: install vim-plug if not present
if empty(glob('~/.config/nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  autocmd VimEnter * PlugInstall
endif

"Note: Skip initialization for vim-tiny or vim-small.
if !1 | finish | endif
if has('vim_starting')
  set nocompatible               " Be iMproved
  " Required:
  call plug#begin()
endif

Plug 'zefei/cake16'
Plug 'zefei/vim-colortuner'


" Add plugins to &runtimepath
call plug#end()

colorscheme cake16
```

save this somewhere, and make sure to run neovim with the dedicated minimal config like this:
`neovim -u <minimal_neovim_config_filepath> ~/.zshrc`

**Comment by zefei** [comment]
@alexanderjeurissen thanks for looking at this and having a minimal config repro! I'll take a look when I have time. The interaction between neovim true color and colortuner hasn't been very stable for me, as I sometimes saw them break in different ways.

**Comment by alexanderjeurissen** [comment]
@zefei do you have any update on this ? this weird behaviour drove me to use a different colorscheme for the time being, but I'd love to have my cake and eat it too if you catch my drift..

**Comment by zefei** [comment]
Hey @alexanderjeurissen,

I'm so sorry for the delay, that totally slipped my mind. I just pushed a fix for this problem. Can you check if it's fixed? Again, thanks for the repro and support!

**Comment by alexanderjeurissen** [comment]
Issue seems fixed, at least I'm not able to reproduce it. Thanks for your quick response !!
